apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  labels:
    component: etcd
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: etcd
    image: registry.k8s.io/etcd:3.6.5-0
    imagePullPolicy: IfNotPresent
    command:
    - etcd
    args:
    - --advertise-client-urls=http://$(HOST_IP):2379
    - --listen-client-urls=http://0.0.0.0:2379
    - --data-dir=/var/lib/etcd
    - --listen-peer-urls=http://0.0.0.0:2380
    - --initial-cluster=default=http://$(HOST_IP):2380
    - --initial-advertise-peer-urls=http://$(HOST_IP):2380
    - --initial-cluster-state=new
    - --initial-cluster-token=test-token
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    ports:
    - name: client
      containerPort: 2379
      protocol: TCP
    - name: peer
      containerPort: 2380
      protocol: TCP
    volumeMounts:
    - name: etcd-data
      mountPath: /var/lib/etcd
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        cpu: 200m
        memory: 2Gi
  volumes:
  - name: etcd-data
    hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
