apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    component: kube-scheduler
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: kube-scheduler
    image: registry.k8s.io/kube-scheduler:v1.34.1
    imagePullPolicy: IfNotPresent
    command:
    - kube-scheduler
    args:
    - --bind-address=0.0.0.0
    - --kubeconfig=/var/lib/kubelet/kubeconfig
    - --leader-elect=false
    - --v=2
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    volumeMounts:
    - name: kubeconfig
      mountPath: /var/lib/kubelet/kubeconfig
      readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
  volumes:
  - name: kubeconfig
    hostPath:
      path: /var/lib/kubelet/kubeconfig
      type: FileOrCreate
