---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-system-oci
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/vkamlov/flux-gitops-dev
  ref:
    semver: '>=0.0.x-0'
  secretRef:
    name: ghcr-registry-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-oci
  namespace: flux-system
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
spec:
  force: false
  interval: 1m0s
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system-oci
