# Use this config as a template in order to  use Instance Principals based aithentication
# (https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Tasks/callingservicesfrominstances.htm).
# Ensure you have setup the following OCI policies and your kubernetes nodes are running within them
# allow dynamic-group [your dynamic group name] to read instance-family in compartment [your compartment name]
# allow dynamic-group [your dynamic group name] to use virtual-network-family in compartment [your compartment name]
# allow dynamic-group [your dynamic group name] to manage load-balancers in compartment [your compartment name]
useInstancePrincipals: true

# compartment configures Compartment within which the cluster resides.
# Using tenancy OCID (root compartment) where the instance actually is
compartment: ocid1.tenancy.oc1..aaaaaaaa26qtlqgijdvb27qelffw4njv75ho5jhl24kktuvcoejqzgczqdba

# vcn configures the Virtual Cloud Network (VCN) within which the cluster resides.
vcn: ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaay4dbhtaaezrwfn37fy4zej6hocl5j62ag42fkjcvp34yf22iddta

loadBalancer:
  # subnet1 configures one of two subnets to which load balancers will be added.
  # For regional subnets (AD = null), only subnet1 is needed
  subnet1: ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaa6jsjzx66oqct2txyy6o2jfpxzs6sn6fujapqscfauv2tamglvc5q
  # subnet2: Only needed for AD-specific subnets, not for regional subnets
  # subnet2: ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaanso7ojfferfieewt7vpdvzird5lpc2saun7t6ppuor4hl5pecgea
  # SecurityListManagementMode configures how security lists are managed by the CCM.
  # If you choose to have security lists managed by the CCM, ensure you have setup the following additional OCI policy:
  # Allow dynamic-group [your dynamic group name] to manage security-lists in compartment [your compartment name]
  #
  #   "All" (default): Manage all required security list rules for load balancer services.
  #   "Frontend":      Manage only security list rules for ingress to the load
  #                    balancer. Requires that the user has setup a rule that
  #                    allows inbound traffic to the appropriate ports for kube
  #                    proxy health port, node port ranges, and health check port ranges.
  #                    E.g. 10.82.0.0/16 30000-32000.
  #   "None":          Disables all security list management. Requires that the
  #                    user has setup a rule that allows inbound traffic to the
  #                    appropriate ports for kube proxy health port, node port
  #                    ranges, and health check port ranges. E.g. 10.82.0.0/16 30000-32000.
  #                    Additionally requires the user to mange rules to allow
  #                    inbound traffic to load balancers.
  securityListManagementMode: All

  # Optional specification of which security lists to modify per subnet. This does not apply if security list management is off.
  securityLists:
    ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaa6jsjzx66oqct2txyy6o2jfpxzs6sn6fujapqscfauv2tamglvc5q: ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaa4cgehvbiqgr5paiqhcshwnosrpj5iwuu7q6rz6xdkdjlkwf6en4a
# Optional rate limit controls for accessing OCI API
rateLimiter:
  rateLimitQPSRead: 20.0
  rateLimitBucketRead: 5
  rateLimitQPSWrite: 20.0
  rateLimitBucketWrite: 5
