---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newresource-controller
  namespace: newresource-system
  labels:
    app: newresource-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newresource-controller
  template:
    metadata:
      labels:
        app: newresource-controller
    spec:
      serviceAccountName: newresource-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
        - name: manager
          image: vkamlov/new-controller-manager:0.0.1
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect=true
            - --metrics-bind-address=:8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
