---
apiVersion: v1
kind: Namespace
metadata:
  name: newresource-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newresource-controller
  namespace: newresource-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newresource-controller-role
rules:
  # Permissions for NewResource CRD
  - apiGroups:
      - apps.newresource.com
    resources:
      - newresources
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps.newresource.com
    resources:
      - newresources/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - apps.newresource.com
    resources:
      - newresources/finalizers
    verbs:
      - update
  # Permissions for leader election
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newresource-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newresource-controller-role
subjects:
  - kind: ServiceAccount
    name: newresource-controller
    namespace: newresource-system
